.executor-node: &executor-node
  image: node:18
  tags:
    - docker

stages:
  - validation
  - deploy

audit:
  stage: validation
  <<: *executor-node
  allow_failure: true
  script:
    - npm audit --audit-level=moderate

outdated:
  stage: validation
  <<: *executor-node
  allow_failure: true
  script:
    - npm outdated

test:
  stage: validation
  <<: *executor-node
  script:
    - npm ci
    - npm test

lint:
  stage: validation
  <<: *executor-node
  script:
    - npm ci
    - npm run lint

deploy:
  stage: deploy
  <<: *executor-node
  only:
    variables:
      - $STACK
  when: manual
  script:
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install
    - aws --version
    # install dependencies & deploy
    - npm ci
    - export NODE_ENV=production
    - npm run deploy
